[target.'cfg(all())']
rustflags = [
    "-Dclippy::print_stdout",
    "-Dclippy::print_stderr",
    "-Dclippy::dbg_macro",
    "--print", "native-static-libs",
]

[target.'cfg(target_arch = "aarch64")']
rustflags = [
    "-L", "native=/lib/native-libs",
    "-C", "target-feature=+aes,+crypto,+neon",
]

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+aes,+pclmulqdq,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+fma,+adx",
]