[target.'cfg(all())']
rustflags = [
    "-Dclippy::print_stdout",
    "-Dclippy::print_stderr",
    "-Dclippy::dbg_macro",
]

[target.aarch64-unknown-linux-musl]
rustflags = ["-L", "native=/lib/native-libs"]
