[target.'cfg(all())']
rustflags = [
    "-Dclippy::print_stdout",
    "-Dclippy::print_stderr",
    "-Dclippy::dbg_macro",
]

[target.aarch64-unknown-linux-musl]
rustflags = ["-L", "native=/lib/native-libs", "--cfg", "aes_armv8"]

[target.x86_64-unknown-linux-gnu]
# Always use AES-NI
# https://docs.rs/aes/0.8.1/aes/#x86x86_64-intrinsics-aes-ni
rustflags = ["-C", "target-feature=+aes,+ssse3"]